MetallicFocus/team_zero_application

initial_report_latex/Aims.tex
initial_report_latex/Collaboration.tex
initial_report_latex/ConflictHandling.tex
initial_report_latex/Initial report.tex
initial_report_latex/Progress.tex
initial_report_latex/Schedule.tex

layout of initial report in latex added

initial report layout

---

Android/app/build.gradle
Android/app/src/main/AndroidManifest.xml
Android/app/src/main/java/teamzero/chat/mobile/Chat.java
Android/app/src/main/java/teamzero/chat/mobile/ChatList.java
Android/app/src/main/java/teamzero/chat/mobile/MainActivity.java
Android/app/src/main/java/teamzero/chat/mobile/NewChat.java
Android/app/src/main/java/teamzero/chat/mobile/Registration.java
Android/app/src/main/res/drawable/ic_search_icon.xml
Android/app/src/main/res/layout/chat_layout.xml
Android/app/src/main/res/layout/chat_list_layout.xml
Android/app/src/main/res/layout/new_chat_layout.xml
Android/app/src/main/res/menu/menu_layout.xml
Android/app/src/main/res/values/strings.xml
Android/app/src/main/res/xml/searchable.xml

1) The chat list can display information on both rows now (by using both TextViews of simple_list_item_2 through overriding the getView method of ArrayAdapter)
2) Added an incipit form of search bar (implemented a searchable configuration)
3) Added New Chat and Chat activities (layouts with basic functionalities)
- Implemented generic web sockets and tested through a demo URI.

Improved UI and implemented web sockets

---

Android/app/src/main/java/teamzero/chat/mobile/MainActivity.java
Android/app/src/main/java/teamzero/chat/mobile/Registration.java
Android/app/src/main/java/teamzero/chat/mobile/WebSocket.java
Android/app/src/main/java/teamzero/chat/mobile/WebSocketHandler.java

- Implemented a handler for web sockets in order to pass the session throughout the application (as web sockets are not serializable/parcelable)

Implemented web socket handler

---

Android/app/src/main/java/teamzero/chat/mobile/WebSocket.java

- Changed from hardcoded sleep time to waiting exactly until WS connection is successful within time limit.

Used ExecutorService to wait until WS is opened

---

ServerTesterClient/src/Client.java
ServerTesterClient/src/ClientRegisterLoginAndMessageTest.java
TeamZeroServer/src/server/ClientManager.java
TeamZeroServer/src/server/DbConnection.java
TeamZeroServer/src/server/ServerMain.java

Added 3 client test scenarios (more should be added later)
-1- clients register, login, one sends the other a message successfully, then both unregister.
-2- clients register, one logs in and sends the other a message, the other logs in and receives the message on login successfully, then both unregister.
-3- client registers, then tries to login with an incorrect password
DbConnection: changed add/delete methods to return boolean stating whether or not transaction was successful, so that some feedback can be returned to the user. 
ServerMain: fixed various logic errors and bugs that came up from testing. Changed the map of unsent messages to use usernames as a key rather than user ID, as the user ID would require a costly database search to get (although now we run into the problem of …

Added various test scenarios and fixed bugs that came up

---

Android/app/build.gradle
Android/app/src/main/java/database/AppDatabase.java
Android/app/src/main/java/database/AppDatabaseClient.java
Android/app/src/main/java/database/StoredChatList.java
Android/app/src/main/java/database/StoredChatListDao.java
Android/app/src/main/java/teamzero/chat/mobile/ChatList.java
Android/app/src/main/java/teamzero/chat/mobile/NewChat.java
Android/app/src/main/res/drawable/ic_user_default_avatar.xml
Android/app/src/main/res/menu/menu_layout.xml
Android/app/src/main/res/values/strings.xml
Android/build.gradle

- Implemented a local SQLite database using Android Room 1.1.1
- Created chat list table with it's associated CRUD operations
- Extended menu - Added Sign Out, Unregister and Delete Chats features
- Small design changes
- Added a few tests
- **No longer using Volley**

Implemented local database and added sign out, unregister and delete chats features

---

ServerTesterClient/src/Client.java
ServerTesterClient/src/ClientRegisterLoginAndMessageTest.java
TeamZeroServer/src/server/DbConnection.java
TeamZeroServer/src/server/ServerMain.java

- Added a case to ServerMain to allow for the searchcontacts JSON request which will contain a search query that will search the database for usernames that match the query. The server returns a list of contacts, similar to getallcontacts JSON request.
-added a test case to the test project

added search contacts JSON request functionality and tests

---

ServerTesterClient/src/Client.java
TeamZeroServer/src/server/DbConnection.java
TeamZeroServer/src/server/ServerMain.java

Added changes discussed today/yesterday.
-fixed uppercase contact search issue
-added success reply to text messages
-added timestamp to messages

Server dev

---

Android/app/src/main/java/teamzero/chat/mobile/Chat.java
Android/app/src/main/java/teamzero/chat/mobile/ChatList.java
Android/app/src/main/java/teamzero/chat/mobile/MainActivity.java
Android/app/src/main/java/teamzero/chat/mobile/NewChat.java
Android/app/src/main/java/teamzero/chat/mobile/Registration.java
Android/app/src/main/java/teamzero/chat/mobile/UserDetails.java
Android/app/src/main/java/teamzero/chat/mobile/WebSocket.java
Android/app/src/main/java/tools/JSONConstructor.java
Android/app/src/main/java/users/data/OtherUsersData.java
Android/app/src/main/res/drawable/incoming_message.xml
Android/app/src/main/res/drawable/outgoing_message.xml
Android/app/src/main/res/layout/chat_layout.xml
Android/app/src/main/res/layout/new_chat_layout.xml
Android/app/src/main/res/values/strings.xml

- Finished the implementation of essential user actions (Registration, Login, Unregistration, Send Messages) and tested them
- The user can search for a person to chat with (get a full list using `GETALLCONTACTS` or search for a specific user using `SEARCHCONTACTS`) and the initiated chat will be saved to his local database
- Used `ExecutorService` to wait for responses from server (other than `TEXT` type JSON) and removed all fixed sleep periods 
- Implemented asynchronous runnable action for message retrieval from another user
- Display received text message on screen from other user
- Fixed the user retrieval ListView constraints
- Added small tweaks in design

Implemented user actions to latest version

---

Android/app/src/main/java/teamzero/chat/mobile/Chat.java
Android/app/src/main/java/teamzero/chat/mobile/ChatList.java
Android/app/src/main/java/teamzero/chat/mobile/UserDetails.java
Android/app/src/main/java/teamzero/chat/mobile/WebSocket.java

1) Solved a bug where the last received message could be seen on wrong chats
2) Correctly display all received messages while offline when the user enters the appropriate chat
3) Implemented an unread message notifier

Unread message notifier and fixed the messages received after logging back in

---

ServerTesterClient/src/Client.java
ServerTesterClient/src/ClientRegisterLoginAndMessageTest.java
TeamZeroServer/src/server/Client.java
TeamZeroServer/src/server/DbConnection.java
TeamZeroServer/src/server/ServerMain.java

Clients must register with a publicKey attribute from now on, but it can be left empty (for now).
When clients send getAllContacts or searchContacts requests, the returned result will include publicKeys for new users (users registering from now onwards).
Also updated the server test client a bit to be able to test this.

Added public key field to client object.

---

TeamZeroServer/.settings/org.eclipse.wst.common.project.facet.core.xml

Deleted tomcat runtime requirement

changed settings as server does not require tomcat to run

---

Android/app/build.gradle
Android/app/src/main/java/database/AppDatabase.java
Android/app/src/main/java/database/StoredChatList.java
Android/app/src/main/java/database/StoredChatListDao.java
Android/app/src/main/java/database/UsersOnDevice.java
Android/app/src/main/java/database/UsersOnDeviceDao.java
Android/app/src/main/java/teamzero/chat/mobile/ChatList.java
Android/app/src/main/java/teamzero/chat/mobile/MainActivity.java
Android/app/src/main/java/teamzero/chat/mobile/NewChat.java
Android/app/src/main/java/teamzero/chat/mobile/Registration.java
Android/app/src/main/java/teamzero/chat/mobile/WebSocket.java
Android/app/src/main/java/tools/AESUtilities.java
Android/app/src/main/java/tools/DHUtilities.java
Android/app/src/main/java/tools/RSAUtilities.java

- Started the implementation of encryption protocols within the Android client infrastructure.
- Added RSA, Diffie-Hellman and AES support tools and initiated the retrieval / sending of encoded public keys from / to the server.
- Added the decode method for retrieved public keys from the server in Base64 format.
- The client stores the generated private keys in a local database.
- Added a new table `UsersOnDevice` that stores the users that registered on this device with their respective private keys.
- When unregistering, the users are deleted from the local database with all their information (including chats).
- Chats that are newly initialised and do not belong to a user (but another user opened one and sent a message) are now automatically created for the other user too.
- Added a …

First part of encryption and other features

---

ServerTesterClient/src/Client.java
ServerTesterClient/src/ClientRegisterLoginAndMessageTest.java
TeamZeroServer/src/server/ChatMessage.java
TeamZeroServer/src/server/ClientManager.java
TeamZeroServer/src/server/DbConnection.java
TeamZeroServer/src/server/ServerMain.java
TeamZeroServer/src/serverTests/ServerMainTest.java

Added message history retrieval. Details for clients JSON request (also in the WIKI):
{
type: "GETCHATHISTORY",
myUsername: "", 
theirUsername: "",
historyDays: ""
}
and the reply from server will include a JSON array:
{
type: "GETCHATHISTORY", 
reply:  GETCHATHISTORY + "SUCCESS" or "FAILURE (+ reason if failure), 
messages: [ 
{sender: "senderUsername",
recipient: "recipientUsername",
message: "msg",
timestamp: "yyyy-MM-dd HH:mm:ss"},
{sender: "senderUsername",
recipient: "recipientUsername",
message: "msg",
timestamp: "yyyy-MM-dd HH:mm:ss"}]
}

Added message history retrieval

---

Android/app/src/main/java/teamzero/chat/mobile/Chat.java
Android/app/src/main/java/teamzero/chat/mobile/WebSocket.java
Android/app/src/main/java/tools/AESUtilities.java

Implemented AES encryption and decryption of user messages with a 128 bit temporary hardcoded dummy key.
May fail if trying to decrypt unencrypted messages

Android dev enc

---

ServerTesterClient/.classpath
ServerTesterClient/.settings/org.eclipse.wst.common.project.facet.core.xml
ServerTesterClient/src/Client.java
ServerTesterClient/src/ClientRegisterLoginAndMessageTest.java
ServerTesterClient/src/GroupCreateMethodsTestStrings.java
ServerTesterClient/src/GroupTest.java
TeamZeroServer/src/server/DbConnection.java
TeamZeroServer/src/server/Group.java
TeamZeroServer/src/server/ServerMain.java

sender and recipient usernames are now returned correctly

Server dev - fixed get chat history bug

---

Android/app/src/androidTest/java/teamzero/chat/mobile/JSONConstructorInstrumentedTests.java
Android/app/src/main/java/database/UsersOnDeviceDao.java
Android/app/src/main/java/teamzero/chat/mobile/Chat.java
Android/app/src/main/java/teamzero/chat/mobile/ChatList.java
Android/app/src/main/java/teamzero/chat/mobile/NewChat.java
Android/app/src/main/java/teamzero/chat/mobile/Registration.java
Android/app/src/main/java/teamzero/chat/mobile/WebSocket.java
Android/app/src/main/java/tools/AESUtilities.java
Android/app/src/main/java/tools/DHUtilities.java
Android/app/src/main/java/tools/JSONConstructor.java
Android/app/src/main/java/tools/RFC5114KeyData.java
Android/app/src/main/java/tools/RSAUtilities.java

- Implemented AES encryption and decryption using AES CBC PKCS7Padding on 128 bits with hardcoded keys and IV's
- Started the implementation of key generation / key exchange in Diffie-Hellman only
- Added the GETPUBLICKEY JSON request to retrieve the public keys of other users when the chat is initialised by them
- Better integration with old test accounts that do not have a public key
- Finished the list of instrumented tests for JSON request building

AES Encryption Alignment

---

Android/app/src/androidTest/java/teamzero/chat/mobile/JSONConstructorInstrumentedTests.java
Android/app/src/main/java/teamzero/chat/mobile/Chat.java
Android/app/src/main/java/teamzero/chat/mobile/ChatList.java
Android/app/src/main/java/teamzero/chat/mobile/MainActivity.java
Android/app/src/main/java/teamzero/chat/mobile/UserDetails.java
Android/app/src/main/java/teamzero/chat/mobile/WebSocket.java
Android/app/src/main/java/tools/JSONConstructor.java
Android/app/src/main/res/menu/menu_layout.xml
Android/app/src/main/res/values/strings.xml

- Implemented the retrieval of chat history through `GETCHATHISTORY` JSON request to server
- Squished a bug where the history would not be shown when there was a single message retrieved from the server
- Implemented a new setting where the user can hide the history of chats
- Added instrumented tests for the generation of JSON requests of `GETCHATHISTORY`

Implemented Chat History

---

Android/app/src/main/java/teamzero/chat/mobile/Chat.java
Android/app/src/main/java/teamzero/chat/mobile/WebSocket.java

Added Timestamps and Better Chat Design

---

TeamZeroServer/src/server/DbConnection.java
frontend/src/components/Signin.vue

Adjusted the following methods:
- addUser()
- deleteUser()
- getAllUserInfo()
- getSearchedUsers()
- addNewGroup()
- addGroupMessage()
- addGroupMember()

User left group and unregistered

---

frontend/src/components/Signin.vue
frontend/src/components/Signup.vue
frontend/src/main.js

Please test with new registered accounts, or local device may not have record of private key.

Completed DH+AES on web

---

Android/app/src/main/java/database/StoredChatListDao.java
Android/app/src/main/java/teamzero/chat/mobile/Chat.java
Android/app/src/main/java/teamzero/chat/mobile/ChatList.java
Android/app/src/main/java/teamzero/chat/mobile/NewChat.java
Android/app/src/main/java/teamzero/chat/mobile/Registration.java
Android/app/src/main/java/teamzero/chat/mobile/WebSocket.java
Android/app/src/main/java/tools/AES256Cryptor.java
Android/app/src/main/java/tools/AESUtilities.java
Android/app/src/main/java/tools/DHUtilities.java

- Implemented Diffie-Hellman with fixed keys
- Implemented a method that calculates the shared secret (passphrase) between two shared keys
- Implemented AES encryption/decryption similar to CryptoJS

Implemented Diffie-Hellman Shared Key Calculation + AES

---

TeamZeroServer/src/server/DbConnection.java
TeamZeroServer/src/server/ServerMain.java
frontend/src/components/Signin.vue
frontend/src/components/group-chat-panel.vue
frontend/src/components/group-chat.vue
frontend/src/components/single-message-from-group.vue

Added to server 2 methods:
- Get history for groups
- Get groups that the user is in
In web-app:
Sending messages in groups now working
Adding members to groups after creation is working but there are a few bugs

Add group functionality to web app.

---

Android/app/src/main/java/teamzero/chat/mobile/Chat.java
Android/app/src/main/java/teamzero/chat/mobile/ChatList.java
Android/app/src/main/java/teamzero/chat/mobile/MainActivity.java
Android/app/src/main/java/teamzero/chat/mobile/NewChat.java
Android/app/src/main/java/teamzero/chat/mobile/Registration.java
Android/app/src/main/java/teamzero/chat/mobile/WebSocket.java

1) On `MainActivity` and `ChatList` -- Disabled the native back button and replaced the functionality with a sensible message to the user
2) The rest of activities -- Replaced with a proper way to end the current activity and go back to the parent one

Native back button behaviour change
